[platformio]
default_envs = esp32c3
src_dir = src

[env]
lib_extra_dirs = ..
lib_deps = h2zero/NimBLE-Arduino@2.5.0
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=0

[env:esp32]
platform = espressif32@7.0.1
board = esp32dev

[env:esp32c3]
platform = espressif32@7.0.1
board = esp32-c3-devkitm-1

[env:esp32c3_broadcaster]
extends = env:esp32c3
build_flags =
    ${env.build_flags}
    -DCONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
    -DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCONFIG_BT_NIMBLE_LOG_LEVEL=5
    -DCONFIG_NIMBLE_CPP_LOG_LEVEL=0

[env:esp32c3_minimal]
extends = env:esp32c3_broadcaster
build_flags =
    ${env:esp32c3_broadcaster.build_flags}
    -DFINDMYADV_DISABLE_BUILTIN_ACCELEROMETER=1

[env:esp32c3_bluedroid]
extends = env:esp32c3
build_flags =
    ${env.build_flags}
    -DFINDMYADV_USE_BLUEDROID=1

[env:esp32s3]
platform = espressif32@7.0.1
board = lolin_s3_mini

[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/3.3.9/esp32-core-3.3.9.tar.xz
board = esp32-c6-devkitc-1
board_upload.flash_size = 4MB
